// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UserCrudApp.Data;

#nullable disable

namespace UserCrudApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251225075905_Add2FAFieldsToUsers")]
    partial class Add2FAFieldsToUsers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UserCrudApp.Models.Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("createdt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("createuid")
                        .HasColumnType("int");

                    b.Property<DateTime?>("deldt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("deluid")
                        .HasColumnType("int");

                    b.Property<int?>("lmodifyby")
                        .HasColumnType("int");

                    b.Property<DateTime?>("lmodifydt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("tbl_Users", "dbo");
                });
#pragma warning restore 612, 618
        }
    }
}
